version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: echo_api
      MYSQL_USER: echo_user
      MYSQL_PASSWORD: echo_pass
